In [11]:
!pip install imutils

In [6]:
import cv2
import imutils
import numpy

In [7]:
def CreateTransformationMatrix(view_x, view_y, view_z, width, height):

    # Create a rotation matrix
    view_x1 = (view_x-90) * (numpy.pi / 180)
    view_y1 = (view_y-90) * (numpy.pi / 180)
    view_z1 = (view_z-90) * (numpy.pi / 180)
    R_array = numpy.array([view_x1, view_y1, view_z1])

    R, jacobian = cv2.Rodrigues(R_array)
    R[0][2] = 0
    R[1][2] = 0
    R[2][2] = 1

    #Create and combine with translation matrix
    Trans_Mat = numpy.array([[1, 0, -width/2],
                        [0, 1, -height/2],
                        [0, 0, 1]])

    R_T_Mat = numpy.dot(R, Trans_Mat)
    R_T_Mat[2][2] += height

    #Create and combine with camera matriview_x
    Intrinsic_Mat = numpy.array([[height, 0, width/2],
                           [0, height, height/2],
                           [0, 0, 1]])

    print(Intrinsic_Mat.__class__.__name__, Intrinsic_Mat.shape, R_T_Mat.__class__.__name__, R_T_Mat.shape)
    rotation_matrix = numpy.dot(Intrinsic_Mat, R_T_Mat)
    return rotation_matrix

def RotateAndDisplayImage(img, img_width, img_height, Dview=[90,90,90]):
    M_Transformation_Matrix = CreateTransformationMatrix(Dview[0], Dview[1], Dview[2], img_width, img_height)
    print("M_Transformation_Matrix", M_Transformation_Matrix)
    persp = cv2.warpPerspective(img, M_Transformation_Matrix, (img_width, img_height))
    return persp

In [8]:
#NOTE FOR LATER: Try (97, 86, 72)
fn = "../../Data/VideoFrames/frame360.jpg"

view_rot = [97.0,86.0,72.0]
im = cv2.imread(fn)
im_h, im_w, im_ch_ct = im.shape
cv2.imwrite("Rectified.jpg",RotateAndDisplayImage(im, im_w,im_h,view_rot))

ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[ 3.54889689e+02  1.44627624e+02 -2.43831883e+04]
 [-1.03497829e+02  3.63263057e+02  2.75370636e+04]
 [ 4.94404100e-02  1.30632829e-01  3.24137180e+02]]


True

## ORIGINAL VERSION OF THE CODE

In [18]:
def CreateTransformationMatrix():

    # Create a rotation matrix
    view_x1 = (view_x-90) * (numpy.pi / 180)
    view_y1 = (view_y-90) * (numpy.pi / 180)
    view_z1 = (view_z-90) * (numpy.pi / 180)
    R_array = numpy.array([view_x1, view_y1, view_z1])

    R, jacobian = cv2.Rodrigues(R_array)
    R[0][2] = 0
    R[1][2] = 0
    R[2][2] = 1

    #Create and combine with translation matrix
    Trans_Mat = numpy.array([[1, 0, -im_w/2],
                        [0, 1, -im_h/2],
                        [0, 0, 1]])

    R_T_Mat = numpy.dot(R, Trans_Mat)
    R_T_Mat[2][2] += im_h

    #Create and combine with camera matriview_x
    Intrinsic_Mat = numpy.array([[im_h, 0, im_w/2],
                           [0, im_h, im_h/2],
                           [0, 0, 1]])

    print(Intrinsic_Mat.__class__.__name__, Intrinsic_Mat.shape, R_T_Mat.__class__.__name__, R_T_Mat.shape)
    rotation_matrix = numpy.dot(Intrinsic_Mat, R_T_Mat)
    return rotation_matrix

def RotateAndDisplayImage():
    M_Transformation_Matrix = CreateTransformationMatrix()
    print("M_Transformation_Matrix", M_Transformation_Matrix)
    persp = cv2.warpPerspective(im, M_Transformation_Matrix, (im_w, im_h))

    cv2.imshow("Distorted", im)
    cv2.imshow("undistorted", persp)

def ResetX(pos):
    global view_x
    view_x = float(pos)
    RotateAndDisplayImage()

def ResetY(pos):
    global view_y
    view_y = float(pos)
    RotateAndDisplayImage()

def ResetZ(pos):
    global view_z
    view_z = float(pos)
    RotateAndDisplayImage()

fn = "../../Data/VideoFrames/frame360.jpg"

view_x = view_y = view_z = float(90)
im = cv2.imread(fn)
im_h, im_w, im_ch_ct = im.shape
cv2.namedWindow("Distorted")
cv2.namedWindow("undistorted")
cv2.createTrackbar("X axis", "undistorted", int(view_x),180, ResetX)
cv2.createTrackbar("Y axis", "undistorted", int(view_y),180, ResetY)
cv2.createTrackbar("Z axis", "undistorted", int(view_z),180, ResetZ)

RotateAndDisplayImage()

cv2.waitKey(0) & 0xff
cv2.destroyWindow("Distorted")
cv2.destroyWindow("undistorted")

ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[360.   0. 270.]
 [  0. 360. 180.]
 [  0.   0. 361.]]
ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[360.   0. 270.]
 [  0. 360. 180.]
 [  0.   0. 361.]]
ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[360.   0. 270.]
 [  0. 360. 180.]
 [  0.   0. 361.]]
ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[360.   0. 270.]
 [  0. 360. 180.]
 [  0.   0. 361.]]
ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[  359.94517026    -6.28286632  1415.71996793]
 [    6.28286632   359.94517026 -1506.50455184]
 [    0.             0.           361.        ]]
ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[  359.78069773   -12.56381881  2590.69900007]
 [   12.56381881   359.78069773 -3172.75667032]
 [    0.             0.           361.        ]]
ndarray (3, 3) ndarray (3, 3)
M_Transformation_Matrix [[  359.50663251   -18.84094425  3794.5791864 ]
 [   18.84094425   359.50663251 -4818.24879891]
 [    0.        